<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="flow" nsURI="ecore://nasdanika.org/models/flow" nsPrefix="org.nasdanika.models.flow">
  <eClassifiers xsi:type="ecore:EClass" name="ModelElement" abstract="true" eSuperTypes="../../org.nasdanika.ncore/model/ncore.ecore#//DocumentedNamedElementWithID">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Base class for flow model elements"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArtifactDomainElement" abstract="true"
      eSuperTypes="#//ModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ArtifactDomain" abstract="true" eSuperTypes="#//ArtifactDomainElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A group of artifacts"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="artifacts" upperBound="-1"
        eType="#//Artifact" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Artifacts used in this package and sub-packages"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Artifact">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Information passed between flow elements and operated on by participants using resources"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resources" upperBound="-1"
        eType="#//Resource" eOpposite="#//Resource/artifacts">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Resorces which operate with this artifact. E.g. a Java source file artifact is edited in a Java IDE resource and stored in a version control repository resource."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="participants" upperBound="-1"
        eType="#//Participant" eOpposite="#//Participant/artifacts">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Participants which use this artifact"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="infos" upperBound="-1"
        eType="#//ArtifactInfo" eOpposite="#//ArtifactInfo/artifact">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Opposite to ArtifactInfo.artifact - all infos which use this artifact."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataElements" upperBound="-1"
        eType="#//DataElement" eOpposite="#//DataElement/artifacts">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Data element used in this artifact. E.g. a JSON structure may use Person data element/type"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eGenericSuperTypes eClassifier="#//ArtifactDomainElement"/>
    <eGenericSuperTypes eClassifier="#//Collaboratable">
      <eTypeArguments eClassifier="#//Role"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeArtifact" eSuperTypes="#//Artifact">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Artifact containing other artifacts, e.g. a zip file"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//Artifact" containment="true" eKeys="../../org.nasdanika.ncore/model/ncore.ecore#//DocumentedNamedElementWithID/id"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArtifactInfo" eSuperTypes="#//ModelElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Information about input/output artifact"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="artifact" lowerBound="1"
        eType="#//Artifact" eOpposite="#//Artifact/infos">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Artifact"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resources" upperBound="-1"
        eType="#//Resource" eOpposite="#//Resource/infos">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Resources used to work on the artifact or store the artifact"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="participants" upperBound="-1"
        eType="#//Participant" eOpposite="#//Participant/infos">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Participants working on the artifact using resources - an alternative to roles"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Connection" eSuperTypes="#//ModelElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Base class for Transitions and Calls. Contained by its source."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//Target"
        eOpposite="#//Target/incomingConnections">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Connection target"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArtifactProducer" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputs" upperBound="-1"
        eType="#//ArtifactInfo" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Information about produced artifacts"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessElement" eSuperTypes="#//ModelElement ../../org.nasdanika.models.capability/model/capability.ecore#//RequirementConsumer"/>
  <eClassifiers xsi:type="ecore:EClass" name="Source" abstract="true" interface="true"
      eSuperTypes="#//ArtifactProducer">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Source of connections"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingConnections" upperBound="-1"
        eType="#//Connection" containment="true" eKeys="../../org.nasdanika.ncore/model/ncore.ecore#//DocumentedNamedElementWithID/id">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Source outgoing connections"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Start" eSuperTypes="#//ProcessElement #//Source">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Start pseudo-state"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputPort" eSuperTypes="#//ModelElement #//Source">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Nodes may have input ports and connections may use input ports as targets"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArtifactConsumer" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputs" upperBound="-1"
        eType="#//ArtifactInfo" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Inputs to this target coming from one or more connections"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Target" abstract="true" interface="true"
      eSuperTypes="#//ArtifactConsumer">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Base class for connection targets"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incomingConnections" upperBound="-1"
        eType="#//Connection" eOpposite="#//Connection/target">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Incoming connections - opposite to Connection.target"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="End" eSuperTypes="#//ProcessElement #//Target">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="End pseudo-state"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OutputPort" eSuperTypes="#//ModelElement #//Target">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Nodes may have output ports with connection starting from those ports"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArtifactProcessor" abstract="true" interface="true"
      eSuperTypes="#//ArtifactProducer #//ArtifactConsumer"/>
  <eClassifiers xsi:type="ecore:EClass" name="Collaboratable" abstract="true" interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Something that particpants in roles can collaborate on"/>
    </eAnnotations>
    <eTypeParameters name="R">
      <eBounds eClassifier="#//Role"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roles" upperBound="-1"
        containment="true" eKeys="../../org.nasdanika.ncore/model/ncore.ecore#//DocumentedNamedElementWithID/id">
      <eGenericType eTypeParameter="#//Collaboratable/R"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Role" eSuperTypes="#//ModelElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A role of a participant in collaboration with other particpants in roles"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="participants" upperBound="-1"
        eType="#//Participant" eOpposite="#//Participant/roles">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Participants playing this role"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resources" upperBound="-1"
        eType="#//Resource" eOpposite="#//Resource/roles">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Resources used by this role"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArtifactProcessorRole" eSuperTypes="#//Role #//ArtifactProcessor">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A role which works on artifacts"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Node" abstract="true" eSuperTypes="#//ProcessElement #//Source #//Target #//ArtifactProcessor">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A flow element which supports both outgoing and incoming connections"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputPorts" upperBound="-1"
        eType="#//InputPort" containment="true" eKeys="../../org.nasdanika.ncore/model/ncore.ecore#//DocumentedNamedElementWithID/id">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Input ports may be used to group incoming connections"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputPorts" upperBound="-1"
        eType="#//OutputPort" containment="true" eKeys="../../org.nasdanika.ncore/model/ncore.ecore#//DocumentedNamedElementWithID/id">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Output ports can be used to group outgoing connections"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Gateway" eSuperTypes="#//Node">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A flow element which can combine (join) and dispatch (fork) its inputs"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Service" eSuperTypes="#//Node">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A flow element which references a (shared) process"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="process" eType="#//Process"
        eOpposite="#//Process/services">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A process which this service represents"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transition" eSuperTypes="#//Connection">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Transition passes control and payload from its source to its target. Fire-and-forget semantics."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="payload" upperBound="-1"
        eType="#//ArtifactInfo">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Transition palyoad - references to source outputs"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Call" eSuperTypes="#//Transition">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Sends a request payload to its target and returns response to its source. Request-response semantics."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="response" upperBound="-1"
        eType="#//ArtifactInfo">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Call response - references to target outputs"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Activity">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="An activity is performed by participants in roles using resources and input artifacts to produce output artifacts"/>
    </eAnnotations>
    <eGenericSuperTypes eClassifier="#//Node"/>
    <eGenericSuperTypes eClassifier="#//ArtifactProcessorRole"/>
    <eGenericSuperTypes eClassifier="#//Collaboratable">
      <eTypeArguments eClassifier="#//ArtifactProcessorRole"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessDomainElement" abstract="true"
      eSuperTypes="#//ModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessDomain" abstract="true" eSuperTypes="#//ProcessDomainElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A group of processes"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="processes" upperBound="-1"
        eType="#//Process" containment="true" eKeys="../../org.nasdanika.ncore/model/ncore.ecore#//DocumentedNamedElementWithID/id">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Flows defined in this package"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Process" eSuperTypes="#//Activity #//ProcessDomainElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Flow is a composite activity"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//ProcessElement" containment="true" eKeys="../../org.nasdanika.ncore/model/ncore.ecore#//DocumentedNamedElementWithID/id">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Flow elements"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="services" upperBound="-1"
        eType="#//Service" eOpposite="#//Service/process">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Services referencing this process"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResourceDomainElement" abstract="true"
      eSuperTypes="#//ModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ResourceDomain" abstract="true" eSuperTypes="#//ResourceDomainElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A group of resources"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resources" upperBound="-1"
        eType="#//Resource" containment="true" eKeys="../../org.nasdanika.ncore/model/ncore.ecore#//DocumentedNamedElementWithID/id">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Resources used in activities in this package and sub-packages"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Resource" eSuperTypes="#//ResourceDomainElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Resource is something used by participants/roles to work with artifacts. It may be a tool, or a repository."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="artifacts" upperBound="-1"
        eType="#//Artifact" eOpposite="#//Artifact/resources">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Artifacts which this resource operates with. "/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roles" upperBound="-1"
        eType="#//Role" eOpposite="#//Role/resources">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Roles which use this resource"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="participants" upperBound="-1"
        eType="#//Participant" eOpposite="#//Participant/resources">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Participants using this resource"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="infos" upperBound="-1"
        eType="#//ArtifactInfo" eOpposite="#//ArtifactInfo/resources">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="ArtifactInfo which reference this resource"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeResource" eSuperTypes="#//Resource">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Resource containing other resources, e.g. a file system or a tool suite"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//Resource" containment="true" eKeys="../../org.nasdanika.ncore/model/ncore.ecore#//DocumentedNamedElementWithID/id"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParticipantDomainElement" abstract="true"
      eSuperTypes="#//ModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ParticipantDomain" abstract="true" eSuperTypes="#//ParticipantDomainElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A group of particpants"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="participants" upperBound="-1"
        eType="#//ParticipantDomainElement" containment="true" eKeys="../../org.nasdanika.ncore/model/ncore.ecore#//DocumentedNamedElementWithID/id">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Participants of activities in this package and sub-packages"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Participant" eSuperTypes="#//ParticipantDomainElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Participates in flow execution by playing roles in activities "/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roles" upperBound="-1"
        eType="#//Role" eOpposite="#//Role/participants">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Roles played by this participant"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resources" upperBound="-1"
        eType="#//Resource" eOpposite="#//Resource/participants">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Resources used by this participant"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="artifacts" upperBound="-1"
        eType="#//Artifact" eOpposite="#//Artifact/participants">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Artifacts this participant works on"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="infos" upperBound="-1"
        eType="#//ArtifactInfo" eOpposite="#//ArtifactInfo/participants">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Artifact infos referencing this participant. An alternative to using roles."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataTypeDomainElement" abstract="true"
      eSuperTypes="#//ModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataTypeDomain" abstract="true" eSuperTypes="#//DataTypeDomainElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A group of data types"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataTypes" upperBound="-1"
        eType="#//DataType" containment="true" eKeys="../../org.nasdanika.ncore/model/ncore.ecore#//DocumentedNamedElementWithID/id">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Data types used in this package and sub-packages"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Type of data. E.g. Number, Date, Text, Person"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="base" eType="#//DataType"
        eOpposite="#//DataType/extensions">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Base of this data type. E.g. SSN data type may have Text data type as its base."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extensions" upperBound="-1"
        eType="#//DataType" eOpposite="#//DataType/base"/>
    <eGenericSuperTypes eClassifier="#//DataTypeDomainElement"/>
    <eGenericSuperTypes eClassifier="#//Collaboratable">
      <eTypeArguments eClassifier="#//Role"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EcoreDataType" eSuperTypes="#//DataType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A data type defined in Ecore model"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EClassifier">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Type Eclassifier"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataDomainElement" abstract="true" eSuperTypes="#//ModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataDomain" abstract="true" eSuperTypes="#//DataDomainElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A group of data elements"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataElements" upperBound="-1"
        eType="#//DataElement" containment="true" eKeys="../../org.nasdanika.ncore/model/ncore.ecore#//DocumentedNamedElementWithID/id">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Data elements used in this package and sub-packages"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataElement" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Element of data"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lowerBound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Lower bound. E.g. if it is 1 then a data element is mandatory."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upperBound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Upper value. -1 means unlimited."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="artifacts" upperBound="-1"
        eType="#//Artifact" eOpposite="#//Artifact/dataElements">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Data element may be used in multiple artifacts"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eGenericSuperTypes eClassifier="#//DataDomainElement"/>
    <eGenericSuperTypes eClassifier="#//Collaboratable">
      <eTypeArguments eClassifier="#//Role"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComplexDataElement" eSuperTypes="#//DataElement #//DataType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A data element consisting of other data elements, a structure/class"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1"
        eType="#//DataElement" containment="true" eKeys="../../org.nasdanika.ncore/model/ncore.ecore#//DocumentedNamedElementWithID/id">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Elements of the complex data elment. Also known as properties/fields/attributes"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleDataElement" eSuperTypes="#//DataElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A scalar, but may contain multiple values of the same type"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//DataType">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Element's type. E.g. ssn data element may be of SSN data type."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Package" eSuperTypes="#//ModelElement #//ParticipantDomain #//ArtifactDomain #//ResourceDomain #//ProcessDomain #//DataTypeDomain #//DataDomain ../../org.nasdanika.models.capability/model/capability.ecore#//CapabilityDomain">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A group of processes and elements they reference - participants, ..."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subPackages" upperBound="-1"
        eType="#//Package" containment="true" eKeys="../../org.nasdanika.ncore/model/ncore.ecore#//DocumentedNamedElementWithID/id">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Packages may form a hierarchy"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
